version: "1.0"
project:
  name: "fullstack-app"
  type: "fullstack"
  components:
    - llm
    - embedding
    - vector
    - cache
    - queue
    - storage

services:
  # AI Service - LLM and Embeddings
  ai:
    port: 11434
    models:
      - "qwen2.5:3b"
      - "nomic-embed-text"
    default: "qwen2.5:3b"

  # SQL Database - PostgreSQL with pgvector
  database:
    type: postgres
    version: "16"
    port: 5432
    extensions:
      - pgvector
      - uuid-ossp
      - pg_trgm

  # NoSQL Database - MongoDB
  mongodb:
    type: mongodb
    version: "7.0"
    port: 27017
    replica_set: false
    auth_enabled: true

  # Cache Service - Redis
  cache:
    type: redis
    port: 6379
    maxmemory: "256mb"
    maxmemory_policy: "allkeys-lru"
    persistence: false

  # Queue Service - Redis
  queue:
    type: redis
    port: 6380
    maxmemory: "1gb"
    maxmemory_policy: "noeviction"
    persistence: true
    appendonly: true
    appendfsync: "everysec"

  # Object Storage - MinIO
  storage:
    type: minio
    port: 9000
    console: 9001

resources:
  memory_limit: "4GB"
  cpu_limit: "2"

connectivity:
  enabled: false
  mdns:
    enabled: true
  tunnel:
    provider: "cloudflare"
    persist: false

cli:
  show_service_info: true